### ISSUE TITLE
New update renders Citador functions unusable 9/9/2019

### ISSUE THREAD

**Issue by anhxtaiii** [nirewen/Citador#126]
Citador v1.7.21 on Discord 9/9/2019

**Comment by wesleymoura** [comment]
same here, just open the discord and the plugin update and stop work, not show the citador option in the text

**Comment by tryoutuser** [comment]
me too. saw it below title window that says citador gets update then after does not work.

**Comment by Aida-Enna** [comment]
same issue here

**Comment by crwn1337** [comment]
Seems to be a BetterDiscord issue and not the plugin's

**Comment by BuIlDaLiBlE** [comment]
Discord changed quite a few names for classes which broke basically all plugins out there.

**Comment by shinji257** [comment]
I checked my install and while Citador is MIA for me right now I do have a working BBD install and all my other plugins are working fine.  Citador is the only one that is broken for me.  Now then the theme is a totally different story and is being worked on.

This is not a BBD issue.  If Discord updated the classes then it is up to the plugin authors and theme authors to update to accommodate for this.  I can try and do some manual digging to see if I can identify where the issue is at.

**Comment by BuIlDaLiBlE** [comment]
Look at this PR: https://github.com/nirewen/Citador/pull/127
You can wait for merge or update the plugin manually.

**Comment by shinji257** [comment]
Dang.  That was fast.  Yes that works and the quoting appears to work with my quick tests.

**Comment by wesleymoura** [comment]
last update fixed, great work guys :D
