### ISSUE TITLE
Error if another language

### ISSUE THREAD

**Issue by GLADpwnz** [nirewen/Citador#5]
I'm use russian translation discord, getting crush when i add to plugin on folder.
fix this
**- case 'en-US':**
**+ default:**

for all another language.

(sorry for shitty issue markdown)

**Comment by nirewen** [comment]
Ahhh
Thank you
I made it default at first, but I changed values to see if using a different language it would change the strings.
Ah, and you're free to suggest a russian translate to the plugin, instead of using the english one
I would love to add a lot of languages so everybody can use my plugin :D
